spring:
  config:
    import: optional:file:.env.local[.properties]
  application:
    name: oauth

server:
  port: ${SERVER_PORT:8080}

frontend:
  url: ${FRONTEND_URL:http://localhost:3000}

auth:
  service:
    jwks-url: ${AUTH_SERVICE_JWKS_URL:http://localhost:8081}
