package com.maruf.oauth.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

/**
 * MongoDB document representing a local user account.
 * Used when email/password authentication is enabled.
 *
 * @author Maruf Bepary
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "users")
public class User {
    /**
     * Unique identifier generated by MongoDB.
     *
     * @author Maruf Bepary
     */
    @Id
    private String id;

    /**
     * Email address used as the username; indexed for fast lookups.
     *
     * @author Maruf Bepary
     */
    @Indexed(unique = true)
    private String email;

    /**
     * BCrypt-hashed password.
     *
     * @author Maruf Bepary
     */
    private String password;

    /**
     * Display name shown in the UI.
     *
     * @author Maruf Bepary
     */
    private String name;
    
    /**
     * Optional avatar URL stored for parity with OAuth profiles.
     *
     * @author Maruf Bepary
     */
    private String avatarUrl;

    /**
     * Granted roles, typically {@code ROLE_USER}.
     *
     * @author Maruf Bepary
     */
    private List<String> roles;
}
